#!/usr/bin/env python3

#
# This script prints a JSON array containing all non-hidden subdirectories of
# the current working directory. As an example, if the current working
# directory contains the subdirectories "foo", "bar" and "baz", the output
# will be (the order of the directories is not necessarily alphabetical):
#
# ["foo", "bar", "baz"]
#
import json

lines = list(open('./.github/scripts/diff.txt').readlines())
outlines = set()

for line in lines:
    outlines.add(line.split('/')[0])

print(json.dumps(list(outlines)))
