#!/usr/bin/env python3

#
# This script prints a JSON array containing all non-hidden subdirectories of
# the current working directory. As an example, if the current working
# directory contains the subdirectories "foo", "bar" and "baz", the output
# will be (the order of the directories is not necessarily alphabetical):
#
# ["foo", "bar", "baz"]
#
import json

lines = list(open('./.github/scripts/diff.txt').readlines())
outlines = set()

#only add items that are directories
for line in lines:
    if line.find(".js") != -1 or line.find(".ts") != -1:
        outlines.add("javascript")


print(json.dumps(list(outlines)))
